# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/

###########################################################################
###########################################################################
###########################################################################
### Site Info.

title = "Jordan M. Wheeler"
description = "Jordan M. Wheeler, Quantitative Methodology Ph.D Student at University of Georgia (UGA)"
baseurl = "/"
googleAnalytics = ""
disqusShortname = ""
theme = "hugo-academic"

# Enter a copyright notice to display in the site footer.
copyright = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687


paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
highlight = true
highlight_languages = ["r", "yaml", "toml", "markdown", "bash"]
  
[outputs]
  home = [ "HTML", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "author"
  
[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.